Models/ErrorViewModel.cs
namespace todo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Todo.cs
namespace Todo.Models;
using System.ComponentModel.DataAnnotations;
public class Todo
{
    //Creator, author
    //title | lable
    //content | main
    //time
    //isDone

    [Required(ErrorMessage = "Lỗi")] //bawcs buoc pphai co
    [MaxLength(5, ErrorMessage = "ten tac gia phai nho hon 5 ki tu")] //do dai lon nhat ten tacs giar
    [MinLength(2)]
    public int Id { get; set; }
    [Required]
    public string Author { get; set; } = string.Empty;
    [Required]
    [MinLength(10)]
    public string Title { get; set; } = string.Empty;
    [Required]
    [MinLength(20)]
    public string Content { get; set; } = string.Empty;
    [Required]
    public DateTime Time { get; set; }
    [Required]

    public bool isDone { get; set; }
    



}

Models/respository.cs
namespace Todo.Models;
public static class Respository
{
    private static int _currentId = 1;
    private static List<Todo> _todolist = new List<Todo>();
    public static IEnumerable<Todo> todolist => _todolist; //return veef todolist

    //viet ham tuowgn tac voi no

    public static void AddTodo(Todo _todo)
    {
        _todo.Id = _currentId;
        _todolist.Add(_todo);
        _currentId ++;

    }

    //xoas
    public static void RemoveTodo( int Id)
    {
       var _itemIndex = _todolist.FindIndex(d=> d.Id == Id);
       if(_itemIndex >0){
           _todolist.RemoveAt(_itemIndex);
       }
    }

    //capnhat
    public static void UpdateTodo(int Id, Todo _todo)
    {
        var _current = _todolist.FirstOrDefault<Todo>(d => d.Id == _todo.Id); //firstordefault tim 1 cai, find la tim nhieu
        if (_current != null)
        {
            _current.Content = _todo.Content;
            _current.Time = _todo.Time;
        }
    }

    //checked da hoan thanh
    public static void CheckDone(int Id){
        var _item = _todolist.FirstOrDefault<Todo>(d=>d.Id == Id);
        if(_item !=null){
            _item.isDone = true;
        }
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using todo.Models;

namespace todo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        ViewData["name"] = "Huy";
        ViewBag.age = 18;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Todo.Models;

namespace Todo.Controllers;

public class TodoController : Controller
{

    public IActionResult Index()
    {
        var model = Respository.todolist;
        return View(model);
    }

    [HttpGet] //ddee truy cập dô form
    public IActionResult TodoForm()
    {
        return View();
    }

    [HttpPost]
    public IActionResult TodoForm(Todo.Models.Todo _todo) //truyen len kieu gi thi no hứng kiểu đó --- ctroller /Models /View /teen bieens
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        Respository.AddTodo(_todo);
        return RedirectToAction("Index");
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/todo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">todo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todo</a> @*doi ctrler, aspcontroller, text *@
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - todo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Todo/Index.cshtml
@model IEnumerable<Todo.Models.Todo>

<h1 class="text-center fw-bold text-uppercase">Todo</h1>  @*/Todo de xem dotnet watch de chay web*@ 
<button class="btn btn-success" type="button">
    <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Todo" asp-action="TodoForm">Todo Form</a>
</button>
<div class="table">
    <thead>
        <tr>
            <th>id</th>
            <th>Author</th>
            <th>Title</th>
            <th>Content</th>
            <th>Time</th>
            <th>isDone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Todo.Models.Todo item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Author</td>
                <td>@item.Title</td>
                <td>@item.Content</td>
                <td>@item.Time</td>
                <td>@item.isDone</td>

            </tr>
        }
    </tbody>
</div>

Views/Todo/TodoForm.cshtml
@model Todo.Models.Todo

<h1 class="text-center fw-bold text-uppercase">Todo Form</h1>
<form asp-controller = "Todo" asp-action="TodoForm" method = "post"> @*neu Todo cung mot controller thi co the bo aspcontroller*@

    <div class="mb-3 form-group">
        <label class = "form-label" asp-for = "Author">Author</label>
        <input class="form-control" asp-for = "Author" type="text" />
        <span asp-validation-for="@Model.Author" class="text-danger"></span>
    </div>
    <div class ="mb-3 form-group">
        <label class = "form-label" asp-for = "Title">Title</label>
        <input class="form-control" asp-for = "Author" type="text" />
    </div>
    <div class ="mb-3 form-group">
        <label class = "form-label" asp-for="Content">Content</label>
        <input class="form-control" asp-for="Content" type="text" />
    </div>
    <div class ="mb-3 form-group">
        <label class = "form-label" asp-for = "Time">Time</label>
        <input asp-for= "Time" type="datetime-local" class="form-control" />
    </div>
    <div class ="mb-3 form-group" form-check>
        <label class = "form-check-label" asp-for = "isDone">Done</label>
        <input asp-for = "isDone" type="checkbox" class="form-check-input" />
    </div>
    <div>
    <button class="btn btn-success" type="submit">Submit</button>
    </div>
</form>